name: Stdlib

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'coq-tactician'
      - uses: coq-community/docker-coq-action@v1.2.3
        with:
          opam_file: 'coq-tactician.opam'
          coq_version: '8.19'
          ocaml_version: '4.13-flambda'
          install: |
            startGroup "Install dependencies"
              opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
              opam pin add -n -y -k path coq-tactician coq-tactician/
              opam remove coq-stdlib -y # Make sure we can build without stdlib
              opam update -y
              opam install -y -j 2 coq-tactician
            endGroup
          script: |
            startGroup "Build"
              yes n | tactician inject
              opam reinstall coq-stdlib --yes
            endGroup
          uninstall: |
            startGroup "Uninstallation test"
              opam remove coq-stdlib --yes
            endGroup
